[races]

	[races.startingRaces]
		#List of races that can be selected through the Race Selection Menu
		#default: ["tensura:human", "tensura:elf", "tensura:dwarf", "tensura:merfolk", "tensura:beastfolk", "tensura:goblin", "tensura:lizardman", "tensura:ogre", "tensura:orc", "tensura:slime", "tensura:wight", "tensura:ghoul", "tensura:lesser_daemon"]
		startingRaces = ["tensura:human", "tensura:elf", "tensura:dwarf", "tensura:merfolk", "tensura:beastfolk", "tensura:goblin", "tensura:lizardman", "tensura:ogre", "tensura:orc", "tensura:slime", "tensura:wight", "tensura:ghoul", "tensura:lesser_daemon"]
		#List of races that can be obtained through picking the "Random" option in the Race Selection Menu
		#default: the same as startingRaces
		possibleRandomRaces = ["tensura:human", "tensura:ogre", "tensura:orc", "tensura:lizardman", "tensura:beastfolk", "tensura:slime", "tensura:merfolk", "tensura:elf", "tensura:dwarf", "tensura:goblin", "tensura:ghoul", "tensura:wight", "tensura:lesser_daemon"]

	[races.TrueDragon]
		#Minimum Possible EP for True Dragon
		#Range: 1.0E7 ~ 1.0E9
		TrueDragonMinEP = 2.0E7
		#Maximum Possible EP for True Dragon
		#Range: 1.0E8 ~ 1.0E9
		TrueDragonMaxEP = 1.0E8

	[races.evolutionRequirements]
		#The amount of EP needed to evolve into a Field Officer
		#Range: 0.0 ~ 1.0E9
		epToFieldOfficer = 100000.0
		#The amount of EP needed to evolve into a General
		#Range: 0.0 ~ 1.0E9
		epToGeneral = 400000.0
		#The amount of EP needed to evolve into a Field Officer
		#Range: 0.0 ~ 1.0E9
		epToGreaterAngel = 100000.0
		#The amount of EP needed to evolve into a General
		#Range: 0.0 ~ 1.0E9
		epToArchAngel = 400000.0
		#The number of Dragon Essences needed to evolve into a Field Officer as a Phantom
		#Range: 0 ~ 10000
		essenceForFieldOfficer = 1
		#The number of Dragon Essences needed to evolve into a General as a Field Officer
		#Range: 0 ~ 10000
		essenceForGeneral = 3
		#The number of Dragon Essences needed to evolve into a Staff Officer as a General
		#Range: 0 ~ 10000
		essenceForStaffOfficer = 10
		#The number of Dragon Essences needed to evolve into a Mystic Angel as a Staff Officer
		#Range: 0 ~ 10000
		essenceForMysticAngel = 20
		#The number of Dragon Essences needed to evolve into a Field Officer as a Lesser Angel
		#Range: 0 ~ 10000
		essenceForFieldOfficerasAngel = 1
		#The number of Dragon Essences needed to evolve into a General as a Greater Angel
		#Range: 0 ~ 10000
		essenceForGeneralasAngel = 4
		#The number of Dragon Essences needed to evolve into a Staff Officer as an Archangel
		#Range: 0 ~ 10000
		essenceForStaffOfficerasAngel = 12
		#The number of Dragon Essences needed to evolve into a Mystic Angel as a Seraphim
		#Range: 0 ~ 10000
		essenceForMysticAngelasAngel = 22

